### ISSUE TITLE
Problem with training Flickr small dataset

### ISSUE THREAD

**Issue by povolann** [hubert0527/infinityGAN#13]
Hello,

I am training to train the small dataset from the paper, but I am getting a mistake:
```
[*] Found lmdb root on local hard drive: /home/anya/Programs/infinityGAN/data/lmdb
Traceback (most recent call last):
  File "train.py", line 798, in <module>
    train_set = MultiResolutionDataset(
  File "/home/anya/Programs/infinityGAN/dataset.py", line 262, in __init__
    self.env = lmdb.open(
lmdb.Error: /home/anya/Programs/infinityGAN/data/lmdb/flickr-landscape-small/train: No such file or directory
```

I have downloaded the data from Google drive and saved them in /home/anya/Programs/infinityGAN/data/lmdb/flickr-landscape-small/train directory, as lock.mdb and data-001.mdb. Or is the configuration wrong?
Thank you for your answer!

**Comment by povolann** [comment]
I have renamed the file data-001.mdb to data.mdb and it is working now.
